### ISSUE TITLE
Cannot import component

### ISSUE THREAD

**Issue by charlielito** [conradbez/streamlit-auth0#11]
Hi, I tried to run this package but got and error. I installed with `pip install streamlit-auth0-component`

The code is

```python
from auth0_component import login_button
import streamlit as st
user_info = login_button(XXX, domain=XXX)
st.write(user_info)
```

The error

```
2022-10-12 14:58:48.291 Uncaught app exception
Traceback (most recent call last):
  File "/home/.venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/home/auth0_app.py", line 1, in <module>
    from auth0_component import login_button
  File "/home/.venv/lib/python3.8/site-packages/auth0_component/__init__.py", line 16, in <module>
    _login_button = components.declare_component("login_button", path=build_dir)
  File "/home/.venv/lib/python3.8/site-packages/streamlit/components/v1/components.py", line 300, in declare_component
    ComponentRegistry.instance().register_component(component)
  File "/home/.venv/lib/python3.8/site-packages/streamlit/components/v1/components.py", line 340, in register_component
    raise StreamlitAPIException(f"No such component directory: '{abspath}'")
streamlit.errors.StreamlitAPIException: No such component directory: '/home/.venv/lib/python3.8/site-packages/auth0_component/frontend/dist'
```

**Comment by grokpot** [comment]
+1

**Comment by grokpot** [comment]
+1
Looks like the /frontend/dist folder doesn't exist:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/1916031/196938579-3d626675-d146-4a6d-af21-41d464216d18.png">

**Comment by charlielito** [comment]
@conradbez :sweat:

**Comment by grokpot** [comment]
Should we fork this project and work on it independently?
Has a lot of potential, but currently broken.

**Comment by charlielito** [comment]
It wasn't broken in previous releases, I think @conradbez can fix it very easily :sweat_smile:

**Comment by conradbez** [comment]
Hey peeps, sorry don't come here all to often but will try to fix issues as I become aware. I've updated to include the dist folder try version `pip install treamlit-auth0-component==0.1.4` and let me know if it still doesn't work :)

**Comment by charlielito** [comment]
It works! Thanks!!
